steps:
  - name: Azure Login
  uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}

  - name: Checkout code
    uses: actions/checkout@v3
    with:
      submodules: recursive

  - name: Install dependencies
    run: npm install

  - name: Build project
    run: npm run build