version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped