# fly.toml app configuration file generated for audityzeroman on 2025-05-19T14:29:32+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'audityzeroman'
primary_region = 'waw'

[build]
  dockerfile = "Dockerfile"


[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
