[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  GIT_LFS_ENABLED = "false"
  PNPM_FLAGS = "--no-frozen-lockfile"

# Build settings with correct pnpm commands
[context.production]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[context.deploy-preview]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[context.branch-deploy]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
