
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audityzer-ingress
  namespace: audityzer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - audityzer.example.com
    secretName: audityzer-tls
  rules:
  - host: audityzer.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: audityzer-service
            port:
              number: 5000
      - path: /mcp
        pathType: Prefix
        backend:
          service:
            name: audityzer-mcp-service
            port:
              number: 8080
