
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audityzer-reports
  namespace: audityzer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
