apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}-auth
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  passwd: {{ include "mqtt-gateway.passwdFile" . | b64enc | quote }}
