{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mqtt-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: websocket
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
