/**
 * TypeScript declaration for walletconnect-provider.js
 * Auto-generated by generate-module-types.js
 */

declare class WalletConnectProvider {
  constructor(options?: any);
  init(): Promise<this>;
  request(args: { method: string; params?: any[] }): Promise<any>;
  on(eventName: string, listener: (...args: any[]) => void): void;
  disconnect(): Promise<boolean>;
  captureState(): any;
  restoreState(state: any): boolean;
  simulateConnection(): Promise<boolean>;
  updateChainId(chainId: string): Promise<boolean>;
}

export { WalletConnectProvider };
