name: Auto-add issues to project

# NOTE: Before using this workflow, you need to:
# 1. Replace the project-url with your actual GitHub project URL
# 2. Create a PAT with project permissions and store it as a repository secret named PROJECT_TOKEN
#    OR use the alternate approach below with GITHUB_TOKEN (has limited permissions)

on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # Replace with your actual project URL
          project-url: https://github.com/users/YOUR_USERNAME/projects/YOUR_PROJECT_NUMBER
          # Option 1: Use a dedicated PAT with project permissions (preferred for org projects)
          # github-token: ${{ secrets.PROJECT_TOKEN }}
          # Option 2: Use the default token (works for personal projects, has limitations)
          github-token: ${{ github.token }}
          # Optional: Configure conditional to only add specific issues
          # labeled-fields-as-options: true
          # label-operator: OR
          # label-prefix: area:
