name: Auto-archive closed items

# NOTE: Before using this workflow, you need to:
# 1. Set up a Personal Access Token (PAT) with project permissions as PROJECT_TOKEN secret
# 2. Set the PROJECT_ID secret with your GitHub project's node ID
#    (You can get this ID using the GitHub GraphQL Explorer)

on:
  schedule:
    # Run weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  archive-closed-items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @octokit/rest @octokit/graphql

      - name: Archive closed items
        env:
          # You need to create these secrets in your repository settings
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment and use the line below if you have a PAT with project permissions
          # GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}

          # Replace with hardcoded value during testing or use repository secret
          PROJECT_ID: 'YOUR_PROJECT_ID' # or ${{ secrets.PROJECT_ID }}
          DAYS_BEFORE_ARCHIVE: 30
        run: |
          node scripts/archive-closed-items.js
