name: Audityzer CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      run_security_tests:
        description: 'Run security tests'
        required: false
        default: true
        type: boolean
      release_dry_run:
        description: 'Dry run (skip publish & npm release job)'
        required: false
        default: false
        type: boolean

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install chromium
        
      - name: Start Audityzer Server
        run: |
          if [ -f "bin/dev-server-runner.js" ]; then
            node bin/dev-server-runner.js start
          else
            npm start &
            sleep 5
          fi
        env:
          SERVER_PORT: 5050
          PUBLIC_DIR: 'public'
          LOG_LEVEL: 'info'
        
      - name: Run Unit Tests
        run: npm test
      
      - name: Stop Audityzer Server
        if: always()
        run: |
          if [ -f "bin/dev-server-runner.js" ]; then
            node bin/dev-server-runner.js stop
          else
            pkill -f "node.*audityzer" || true
          fi
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: |
            test-results/
            coverage/
            
  security_tests:
    name: Run Security Tests
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.run_security_tests != 'false'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install chromium
        
      - name: Start Audityzer Server
        run: |
          if [ -f "bin/dev-server-runner.js" ]; then
            node bin/dev-server-runner.js start
          else
            npm start &
            sleep 5
          fi
        env:
          SERVER_PORT: 5050
          PUBLIC_DIR: 'public'
          LOG_LEVEL: 'info'
          MOCK_MODE: 'true'
        
      - name: Run Security Tests
        run: npm run test:security
        env:
          MOCK_MODE: 'true'
          
      - name: Run Flash Loan Attack Tests
        run: |
          if [ -f "examples/security-bug-tests/flash-loan-attack.test.ts" ]; then
            npx playwright test examples/security-bug-tests/flash-loan-attack.test.ts
          fi
        env:
          MOCK_MODE: 'true'
          
      - name: Run Eth Sign Phishing Tests
        run: |
          if npm run test:phishing 2>/dev/null; then
            npm run test:phishing
          else
            echo "Phishing tests not available"
          fi
        env:
          MOCK_MODE: 'true'
          
      - name: Run Reentrancy Tests
        run: |
          if npm run test:reentrancy 2>/dev/null; then
            npm run test:reentrancy
          else
            echo "Reentrancy tests not available"
          fi
        env:
          MOCK_MODE: 'true'
          
      - name: Stop Audityzer Server
        if: always()
        run: |
          if [ -f "bin/dev-server-runner.js" ]; then
            node bin/dev-server-runner.js stop
          else
            pkill -f "node.*audityzer" || true
          fi
          
      - name: Upload Security Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-test-results
          path: |
            test-results/
            playwright-report/
      
      - name: Generate Security Report
        if: success()
        run: |
          if npm run report:generate 2>/dev/null; then
            npm run report:generate
          else
            echo "Security report generation not available"
          fi
        
      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: security-report
          path: |
            reports/
      
  docker_build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: [test, security_tests]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: audityzer:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Test Docker Image
        run: |
          docker run --name audityzer-test -d -p 5050:5050 audityzer:test
          sleep 10
          curl -s http://localhost:5050/health || curl -s http://localhost:5051/health || echo "Health check failed"
          docker stop audityzer-test
            
  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [test, security_tests]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Package
        run: npm run build
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-package
          path: |
            dist/
            build/
          
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [build, docker_build]
    if: github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && (github.event.inputs.release_dry_run != 'true')
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Download Build Package
        uses: actions/download-artifact@v4
        with:
          name: build-package
          path: dist/
          
      - name: Install Dependencies
        run: npm ci
          
      - name: Check for NPM token
        id: check_token
        run: |
          if [ -n "${{ secrets.NPM_TOKEN }}" ]; then
            echo "npm_token_exists=true" >> $GITHUB_OUTPUT
          else
            echo "npm_token_exists=false" >> $GITHUB_OUTPUT
            echo "::warning::NPM_TOKEN secret not found. Skipping npm publish."
          fi
          
      - name: Version and Publish
        if: steps.check_token.outputs.npm_token_exists == 'true'
        id: version_publish
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version ${{ github.event.inputs.release_type || 'patch' }} -m "Release %s"
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          git push --follow-tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        if: steps.check_token.outputs.npm_token_exists == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version_publish.outputs.VERSION }}
          release_name: Audityzer v${{ steps.version_publish.outputs.VERSION }}
          draft: false
          prerelease: false
          
  deploy_docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
          
      - name: Generate Documentation
        run: |
          mkdir -p public
          if [ -d "docs" ]; then
            cp -r docs public/
          fi
          if [ -f "README.md" ]; then
            cp README.md public/
          fi
          if [ -f "landing-page.html" ]; then
            cp landing-page.html public/index.html
          fi
          if [ -f "CONTRIBUTING.md" ]; then
            cp CONTRIBUTING.md public/
          fi
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
