
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'
  CACHE_DEPENDENCY_PATH: '**/package-lock.json'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run linting
      run: npm run lint:ci

    - name: Run type checking
      run: npm run type-check || echo "Type checking skipped - no TypeScript config found"

    - name: Run unit tests
      run: npm test
      env:
        CI: true

    - name: Run security tests
      run: npm run test:security || echo "Security tests skipped"
      env:
        MOCK_MODE: true

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/
          build/
        retention-days: 7

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./

    - name: Deploy to GitHub Pages (Staging)
      uses: peaceiris/actions-gh-pages@v4
      if: github.repository_owner == 'romanchaa997'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: staging
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./

    - name: Deploy to GitHub Pages (Production)
      uses: peaceiris/actions-gh-pages@v4
      if: github.repository_owner == 'romanchaa997'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true

    - name: Notify deployment success
      run: |
        echo "✅ Production deployment successful!"
        echo "🚀 Application deployed to: https://romanchaa997.github.io/Audityzer"
