
name: Repository Cleanup

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  workflow_dispatch:

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    name: Clean Old Artifacts
    
    steps:
    - name: Delete old artifacts
      uses: actions/github-script@v7
      with:
        script: |
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          
          const cutoff = new Date();
          cutoff.setDate(cutoff.getDate() - 30); // Keep artifacts for 30 days
          
          for (const artifact of artifacts.data.artifacts) {
            if (new Date(artifact.created_at) < cutoff) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
              console.log(`Deleted artifact: ${artifact.name}`);
            }
          }

  cleanup-branches:
    runs-on: ubuntu-latest
    name: Clean Merged Branches
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Delete merged branches
      run: |
        git remote prune origin
        
        # Get list of merged branches (excluding main, develop, and safe-improvements)
        merged_branches=$(git branch -r --merged origin/main | grep -v -E "(main|develop|safe-improvements|HEAD)" | sed 's/origin\///')
        
        for branch in $merged_branches; do
          if [[ ! -z "$branch" ]]; then
            echo "Deleting merged branch: $branch"
            git push origin --delete "$branch" || echo "Failed to delete $branch"
          fi
        done

  security-cleanup:
    runs-on: ubuntu-latest
    name: Security Cleanup
    
    steps:
    - uses: actions/checkout@v4

    - name: Clean sensitive data
      run: |
        echo "Scanning for accidentally committed secrets..."
        
        # Check for common secret patterns
        if grep -r -E "(password|secret|key|token)" --include="*.js" --include="*.json" --include="*.yml" .; then
          echo "Warning: Potential secrets found in code"
        fi
        
        # Clean temporary security scan files
        find . -name "*.security-scan" -delete
        find . -name "*.vulnerability-report" -delete
        
        echo "Security cleanup completed"

  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Security Dependencies
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Update security dependencies
      run: |
        npm audit fix --force
        npm update
        
        # Check if there are changes
        if [[ -n $(git status --porcelain) ]]; then
          git config --local user.email "security@audityzer.com"
          git config --local user.name "Audityzer Security Bot"
          git add package*.json
          git commit -m "chore: update security dependencies [automated]"
          git push
        fi
