
name: Automated Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build application
      run: npm run build

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 22
        extra_plugins: |
          @semantic-release/changelog@6
          @semantic-release/git@10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release-assets:
    name: Create Release Assets
    runs-on: ubuntu-latest
    needs: release
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build release package
      run: |
        npm run build
        npm pack

    - name: Create distribution archive
      run: |
        mkdir -p release-assets
        tar -czf release-assets/audityzer-dist.tar.gz dist/ bin/ lib/ src/core/ src/cli/ package.json README.md LICENSE
        zip -r release-assets/audityzer-dist.zip dist/ bin/ lib/ src/core/ src/cli/ package.json README.md LICENSE

    - name: Get latest release
      id: get_release
      uses: actions/github-script@v7
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1
          });
          if (releases.data.length > 0) {
            return releases.data[0].id;
          }
          return null;

    - name: Upload release assets
      if: steps.get_release.outputs.result != 'null'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ fromJson(steps.get_release.outputs.result).upload_url }}
        asset_path: ./release-assets/audityzer-dist.tar.gz
        asset_name: audityzer-dist.tar.gz
        asset_content_type: application/gzip

  notify-release:
    name: Notify Release
    runs-on: ubuntu-latest
    needs: [release, create-release-assets]
    if: success()
    
    steps:
    - name: Get release info
      id: release_info
      uses: actions/github-script@v7
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1
          });
          if (releases.data.length > 0) {
            const release = releases.data[0];
            core.setOutput('tag_name', release.tag_name);
            core.setOutput('html_url', release.html_url);
            core.setOutput('name', release.name);
          }

    - name: Create release summary
      run: |
        echo "# 🚀 New Release Published!" >> $GITHUB_STEP_SUMMARY
        echo "## Release Details" >> $GITHUB_STEP_SUMMARY
        echo "- **Version**: ${{ steps.release_info.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Name**: ${{ steps.release_info.outputs.name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **URL**: ${{ steps.release_info.outputs.html_url }}" >> $GITHUB_STEP_SUMMARY
        echo "## What's Next?" >> $GITHUB_STEP_SUMMARY
        echo "- Check the release notes for detailed changes" >> $GITHUB_STEP_SUMMARY
        echo "- Update your local installation: \`npm install -g audityzer@latest\`" >> $GITHUB_STEP_SUMMARY
