name: Security Audit

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.npmrc'
      - '.npmrc-ci'
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.npmrc'
      - '.npmrc-ci'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Copy CI-specific npmrc
        run: cp .npmrc-ci .npmrc
        
      - name: Install dependencies
        run: npm ci --ignore-scripts
        
      - name: Run security audit (ignoring known issues)
        run: npm audit --production --audit-level=high || echo "Known issues in dev dependencies - continuing"
        
      - name: Run custom dependency fix script
        run: node scripts/fix-dependencies.js
        
      - name: Run custom vulnerability fix script
        run: node scripts/fix-vulnerabilities.js
        
      - name: Verify production dependencies
        run: |
          result=$(npm audit --production --audit-level=critical)
          if [[ $result == *"found 0 vulnerabilities"* ]]; then
            echo "✅ No critical vulnerabilities found in production dependencies"
            exit 0
          else
            echo "❌ Critical vulnerabilities found in production dependencies!"
            echo "$result"
            exit 1
          fi 