name: Tweet on Release (Disabled)

on:
  # Workflow disabled - uncomment triggers below if needed
  # release:
  #   types: [published]
  # schedule:
  #   # Staggered posts at 00:00, 06:00, 12:00, 18:00 UTC daily
  #   - cron: '0 0 * * *'
  #   - cron: '0 6 * * *'
  #   - cron: '0 12 * * *'
  #   - cron: '0 18 * * *'
  
  # Empty workflow_dispatch allows manual triggering if needed
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps & generate posts
        run: |
          npm ci
          npm run generate:posts

      - name: Read Twitter thread
        id: thread
        run: |
          THREAD=$(cat dist/social/twitter-thread.txt | sed -z 's/\n/\\n/g')
          echo "thread=$THREAD" >> $GITHUB_OUTPUT

      # Twitter posting disabled
      # - name: Post tweets
      #   uses: Eomm/why-don-t-you-tweet@v2
      #   with:
      #     tweet-message: ${{ steps.thread.outputs.thread }}
      #   env:
      #     TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      #     TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      #     TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      #     TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 