name: Tweet on Release

on:
  release:
    types: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps & generate posts
        run: |
          npm ci
          npm run generate:posts

      - name: Read Twitter thread
        id: thread
        run: |
          THREAD=$(cat dist/social/twitter-thread.txt | sed -z 's/\n/\\n/g')
          echo "thread=$THREAD" >> $GITHUB_OUTPUT

      - name: Post tweets
        uses: Eomm/gh-twitter-action@v1
        with:
          msg: ${{ steps.thread.outputs.thread }}
        env:
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }} 