name: Web3 Security Scan

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:
    inputs:
      scan_mode:
        description: 'Scan mode'
        required: true
        default: 'full'
        type: choice
        options:
          - quick
          - standard
          - full
      target_contracts:
        description: 'Target contracts directory'
        required: false
        default: 'contracts'
      l2_validation:
        description: 'Enable L2 validation'
        required: false
        default: true
        type: boolean

env:
  NODE_VERSION: '18.x'

jobs:
  security-scan:
    name: Web3 Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security scan
        run: |
          echo "Running Web3 security scan in ${{ github.event.inputs.scan_mode || 'standard' }} mode"
          npm run security-scan -- --mode=${{ github.event.inputs.scan_mode || 'standard' }} --contracts=${{ github.event.inputs.target_contracts || 'contracts' }}

      - name: Run AI vulnerability detection
        if: ${{ github.event.inputs.scan_mode != 'quick' }}
        run: npm run ai-scan:verbose

      - name: Run L2 validation
        if: ${{ github.event.inputs.l2_validation != 'false' }}
        run: npm run security-validate -- --l2=true

      - name: Generate security report
        run: |
          mkdir -p reports
          npm run viz:report -- --output=reports/security-report

      - name: Archive security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            reports/
            test-results/security/

  deploy-validation:
    name: Deployment Validation
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deployment')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate deployment
        run: npm run deploy-validate -- --check-verification --check-security

      - name: Archive deployment reports
        uses: actions/upload-artifact@v3
        with:
          name: deployment-reports
          path: test-results/deployment/

  bounty-ready:
    name: Prepare Bug Bounty Package
    runs-on: ubuntu-latest
    needs: [security-scan, deploy-validation]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download security reports
        uses: actions/download-artifact@v3
        with:
          name: security-reports
          path: reports/

      - name: Generate Immunefi submission
        run: npm run submit-to-immunefi -- --input=reports/security-report.json

      - name: Generate HackenProof submission
        run: node src/core/bounty-integration/cli.js submit-to-hackenproof --input=reports/security-report.json

      - name: Archive bounty submissions
        uses: actions/upload-artifact@v3
        with:
          name: bounty-submissions
          path: |
            test-results/bounty-submissions/
            reports/bounty-*/
